name: Swift

on: 
  push:
    branches:    
      - main

  pull_request:
    branches:    
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run mockserver
        run: cd MyLibrary; cd Tests; cd MyLibraryTests; cd mockserver; node index.js &
      - name: Run tests
        run: cd MyLibrary; swift test -v